imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

jms_serializer:
  metadata:
    # not clear if loaded (buggy library ?)
    # cache: jms_redis_cache_doctrine_adapter
    cache: file
    debug: false