security:
    role_hierarchy:
        ROLE_LAY_DEPUTY: [ ROLE_DEPUTY ]
        ROLE_PROFESSIONAL_DEPUTY: [ ROLE_DEPUTY ]
        ROLE_AD: [ ROLE_AD ]
        ROLE_ADMIN: [ ROLE_ALLOWED_TO_SWITCH, ROLE_DEPUTY ]

    providers:
        deputy:
           id: deputyprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
           
        passwordManaging:
            pattern:  ^/password-managing*
            security: false   
            
        passwordReset:
            pattern:  ^/user/password-reset/*
            security: false 
            
        userActivate:
            pattern:  ^/user/activate*
            security: false
        
        behatControllers:
            pattern:  ^/behat
            security: false
            
        manageController:
            pattern:  ^/manage/*
            security: false

        secured_area:
            form_login:
                #check_path: /login_check
                login_path: /login
                #username_parameter: login[email]
                #password_parameter: login[password]
            logout:
                path:   /logout
                target: /
                success_handler: logout_listener
                # needed to save custom login params
                invalidate_session: false
            anonymous: ~
            switch_user: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # /admin accessible only from ADMIN, super users and AD users
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_AD] }
        - { path: ^/ad, roles: [ROLE_AD] }
        # open URLs
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-ad, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/feedback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/terms, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/elements, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # all the rest needs authentication
        - { path: ^/ , roles: IS_AUTHENTICATED_FULLY }    
